### ISSUE TITLE
Request to take this codebase over to request it get included in the 2.x Plugins.

### ISSUE THREAD

**Issue by brianddk** [jleight/gpgkee#1]
@jleight This is a great plugin, and I'm very surprised that it never made it into the [official plugin](https://keepass.info/plugins.html) listing.  My main goals will be to expand this plugin with the following MINOR additions:

- [ ] Determine why PLGX builds of this plugin don't register
- [ ] Test cross-os (Windows / Linux / Mac) functionality
- [ ] Add runtime OS detection to switch between Windows / Linux / Mac
- [ ] Publish and maintain binary (DLL or PLGX) releases with GPG signatures
- [ ] Make the build reproducible through Docker
- [ ] Publish a howto or wiki on how to do a reproducible build attestment 
- [ ] Petition to have this listed in the official Keepass2 2.x plugin page

Please let me know your thoughts or concerns about any of these goals, or if you would prefer these be accomplished through PR's here, I'll be happy to work it that way as well.

My fork I will be with is working https://github.com/brianddk/gpgkee

Thx, @brianddk

**Comment by jleight** [comment]
Thanks! I never got around to turning this into much more than just a toy, though there have been a few forks and stars over the years so I guess some people have found it useful. As such, I didn't try to get it listed as an official plugin.

If you want to make some PRs, I'll gladly get them merged in!

**Comment by brianddk** [comment]
Awesome, Thx.  I'll get started on that when free-time rolls back around.  I put some other task I was hoping to do in the list there.

I'm closing out this issue, but if you want to reach me, just post on the [discussion thread](https://github.com/brianddk/gpgkee/discussions/1) I opened in my fork.  That should keep your issue database clean.  Also, if my pestering becomes a nuisance,  you can always create an org to hold this repo and allow me to contribute.  That way you keep control, but reduce the workload.

Either way, and thanks again for great concept!

**Comment by Neustradamus** [comment]
To follow
